config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sessions, only: [:new, :create, :destroy]

  root "cards#index"
  resources :cards
  resources :ideas

  resources :users
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :content, length: { in: 1..15 }, uniqueness: { case_sensitive: false }

  belongs_to :user
end

app/models/idea.rb
class Idea < ApplicationRecord
  before_validation :delete_space
  validates :idea_content, length: { in: 1..30 }, uniqueness: { case_sensitive: false }

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

private
  def delete_space
    idea_content.gsub!(" ", "")
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
  before_save { name.downcase! }
  validates :name, presence: true, length: { in: 1..30 }

  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :ideas, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :your_page, only: [:new, :edit, :show, :destroy]
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = Card.all
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @card.user_id = current_user.id
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_card
      @card = Card.find(params[:id])
    end

    def card_params
      params.require(:card).permit(:content)
    end

    def your_page
      unless logged_in?
        redirect_to new_session_path
      end
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :your_page, only: [:index, :new, :show, :destroy]
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  def index
    @ideas = Idea.all
    @idea = Idea.new

    @cards = Card.all

    @randoms = Card.order("RANDOM()").limit(2)
    @selected_on_card_one = @ideas.where(["card_one = ? or card_two = ?", @randoms[0].content, @randoms[0].content])
    @selected_on_card_two = @ideas.where(["card_one = ? or card_two = ?", @randoms[1].content, @randoms[1].content])
  end


  def show
    @like = current_user.likes.find_by(idea_id: @idea.id)
  end

  def new
    @idea = Idea.new
  end

  def edit
  end

  def create
    @ideas = Idea.all
    @idea = Idea.new(idea_params)
    @idea.user_id = current_user.id

    @cards = Card.all
    @randoms = [Card.find_by(content: @idea.card_one), Card.find_by(content: @idea.card_two)]

    @selected_on_card_one = @ideas.where(["card_one = ? or card_two = ?", @randoms[0].content, @randoms[0].content])
    @selected_on_card_two = @ideas.where(["card_one = ? or card_two = ?", @randoms[1].content, @randoms[1].content])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to ideas_path, notice: 'idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render 'index' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @idea.user_id = current_user.id
    render :edit if @idea.invalid?
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:card_one, :card_two, :idea_content)
  end

  def your_page
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.create(idea_id: params[:idea_id])
    redirect_to like.idea, notice: "#{like.idea.user.name}さんのidea_contentをイイネした"
  end

  def destroy
    like = current_user.likes.find_by(id: params[:id]).destroy
    redirect_to like.idea, notice: "#{like.idea.user.name}さんのイイネを解除した"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :your_page, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def your_page
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :card_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.content %></td>
        <% if card.user.id == current_user.id %>
          <td><%= link_to 'Show', card %></td>
          <td><%= link_to 'Edit', edit_card_path(card) %></td>
          <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= card.user.name %>の投稿</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Card', new_card_path %></p>
<p><%= link_to 'Idea mixer', ideas_path %></p>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @card.content %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<div>今回のお題は。。
  <%= @idea.card_one %>
  <%= @idea.card_two %>
</div>

<%= form_with(model: @idea, local: true) do |form| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idea_content %>
    <%= form.text_field :idea_content, id: :idea_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Idea mixer</h1>

<p id="notice"><%= notice %></p>

<div class="random_records">
  <div>今回のお題は。。。
    <% array = [] %>
    <% @randoms.each do |random| %>
      <%= random.content %>
      <% array << random.id %>
    <% end %>
  </div>
</div>

<div class="input_idea">
  <%= form_for(@idea) do |form| %>
    <% if @idea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% @idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="chosen_cards">
      <%= form.label :card_one %>
      <%= form.text_field :card_one, value: @cards.find(array[0]).content, readonly: "readonly" %>

      <%= form.label :card_two %>
      <%= form.text_field :card_two, value: @cards.find(array[1]).content, readonly: "readonly" %>
    </div>

    <div class="field">
      <%= form.label :idea_content %>
      <%= form.text_field :idea_content, id: :idea_content %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

<div>
  <p>Card oneが被っているもの</p>
  <% @selected_on_card_one.each do |s| %>
  <ul>
    <li><%= s.idea_content %></li>
  </ul>
  <% end %>
</div>

<div>
  <p>Card twoが被っているもの</p>
  <% @selected_on_card_two.each do |s| %>
  <ul>
    <li><%= s.idea_content %></li>
  </ul>
  <% end %>
</div>


<table>
  <thead>
    <tr>
      <th>card_one</th>
      <th>card_two</th>
      <th>idea_content</th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.card_one %></td>
        <td><%= idea.card_two %></td>
        <td><%= idea.idea_content %></td>
        <td><%= link_to "Show", idea_path(id: idea.id) %></td>
        <% if idea.user.id == current_user.id %>
          <td><%= link_to "Edit", edit_idea_path(id: idea.id) %></td>
          <td><%= link_to "Destroy", idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= idea.user.name %>の投稿</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'Cards', cards_path %></p>

app/views/ideas/show.html.erb
<h1>詳細</h1>
<div><%=  @idea.idea_content %></div>

<% unless @idea.user == current_user %>
  <% if @like.present? %>
    <%= link_to like_path(id: @like.id), method: :delete, class: 'btn btn-danger' do %>
      <i class="far fa-thumbs-down"></i>
    <% end %>
  <% else %>
    <%= link_to likes_path(idea_id: @idea.id), method: :post, class: 'btn btn-primary' do %>
      <i class="far fa-thumbs-up"></i>
    <% end %>
  <% end %>
<% end %>

<br>

<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideamixer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <header>
      <% if logged_in? %>
        <p><%= current_user.name %>としてログイン中</p>
        <%= link_to "profile", user_path(current_user.id) %>
        <%= link_to "logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "signup", new_user_path %>
        <%= link_to "login", new_session_path %>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>件のエラーがあります</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "アカウント作成" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<br>

<div class="likes_table">
    <p><i class="far fa-thumbs-up"></i>イイネしたidea_content</p>
    <% @user.likes.each do |l| %>
      <p><%= Idea.all.find(l.idea_id).idea_content %></p>
      <p><%= link_to "詳細", idea_path(l.idea_id) %></p>
    <% end %>

</div>

<br>

<p><%= link_to "アイディア出しカードの登録", root_path %></p>
<p><%= link_to "Idea mixer", ideas_path %></p>